name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: cacevedod/pipeline-templates/.github/workflows/nodejs-ci-template.yml@main
    with:
      run-checkov: true
      run-docker-build: true
      run-docker-push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      # run-sonar: true # Descomenta para activar Sonar
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
