# azure-pipelines.yml

trigger:
  - main
pr:
  - main

pool:
  vmImage: "ubuntu-latest"

resources:
  repositories:
    - repository: templates
      type: github
      name: cacevedod/pipeline-templates
      endpoint: github.com_cacevedod

jobs:
  - template: azure-devops/java-ci-template.yml@templates
    parameters:
      runSonar: false
      runDockerBuild: true
      runDockerPush: ${{ and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main')) }}
