@Library('pipeline-templates@main') _

pipeline {
    agent any
    stages {
        stage('CI para Proyecto Python') {
            steps {
                script {
                    pythonCi(
                        pythonVersion: '3.11',
                        path: 'app',
                        runSonar: true
                    )
                }
            }
        }
    }
}