@Library('pipeline-templates@main') _

pipeline {
    agent {
        docker {
            image 'python:3.11-slim'
            args '-u root:root'
        }
    }
    stages {
        stage('CI para Proyecto Python') {
            steps {
                script {
                    pythonCi(
                        pythonVersion: '3.11',
                        path: 'app',
                        runSonar: true
                    )
                }
            }
        }
    }
}