name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Lint and Build
        run: |
          npm run build
      - name: Run unit tests
        run: npm test
      - name: Upload coverage to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
      - name: Upload JUnit test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: jest-junit.xml
      - name: Build Docker image
        if: github.event_name == 'push'
        run: docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        if: github.event_name == 'push'
        run: docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
