name: Python CI

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: .
      python-version:
        required: false
        type: string
        default: "3.11"
      docker-image-name:
        required: false
        type: string
        default: ghcr.io/${{ github.repository }}:${{ github.sha }}
    secrets: inherit

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest tests/ --cov=app --cov-report=xml --junitxml=test-results.xml
      - name: Upload coverage to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
      - name: Upload JUnit test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: test-results.xml
      - name: Build Docker image
        if: github.event_name == 'push'
        run: docker build -t ${{ inputs.docker-image-name }} .
      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        if: github.event_name == 'push'
        run: docker push ${{ inputs.docker-image-name }}
